version: '3.8'

services:
  nginx:
    depends_on:
      - backend
    image: mank000/amopost_nginx
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    image: mank000/amopost_backend
    command: sh -c " gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - static:/backend_static/

  celery_worker:
    image: mank000/amopost_backend
    command: sh -c " celery -A core worker -l info --concurrency=4"
    depends_on:
      - backend
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    working_dir: /code

  celery_beat:
    image: mank000/amopost_backend
    command: sh -c "celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - backend
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    working_dir: /code

volumes:
  static:

