FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /code

COPY requirements.txt /code/

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn==20.1.0

COPY . /code/

CMD ["gunicorn", "--bind", "0.0.0.0:80", "core.wsgi:application"]
