FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn==20.1.0

COPY . /app/

RUN useradd -ms /bin/bash django
USER django

EXPOSE 8000
# CMD ["gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:8000"]
