# Generated by Django 5.2.6 on 2025-09-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastChatState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_dialog_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Состояние последнего чата',
                'verbose_name_plural': 'Состояние последнего чата',
            },
        ),
    ]
