# Generated by Django 5.2.6 on 2025-09-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastchatstate',
            name='id',
            field=models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
