# Generated by Django 5.2.6 on 2025-09-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farpost', '0002_alter_lastchatstate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastchatstate',
            name='last_dialog_id',
        ),
        migrations.RemoveField(
            model_name='lastchatstate',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='lastchatstate',
            name='id_amocrm',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastchatstate',
            name='id_farpost',
            field=models.CharField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lastchatstate',
            name='is_sended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lastchatstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
