# Generated by Django 5.2.6 on 2025-09-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farpost', '0003_remove_lastchatstate_last_dialog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastchatstate',
            name='last_message',
            field=models.CharField(default=123, max_length=256),
            preserve_default=False,
        ),
    ]
