# Generated by Django 5.2.6 on 2025-09-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farpost', '0004_lastchatstate_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastchatstate',
            name='last_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
