# Generated by Django 5.2.6 on 2025-09-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farpost', '0005_alter_lastchatstate_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastchatstate',
            name='last_out_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
