# Generated by Django 5.2.6 on 2025-10-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farpost', '0006_lastchatstate_last_out_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastchatstate',
            name='uuid_conv',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
