# Generated by Django 5.2.6 on 2025-09-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FARPOST_TOKEN', models.CharField(blank=True, max_length=512, null=True)),
                ('AMOCRM_LONG_TOKEN', models.CharField(blank=True, max_length=1200, null=True)),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
