# Generated by Django 5.2.6 on 2025-09-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='ProjectSettings',
        ),
    ]
