# Generated by Django 5.2.6 on 2025-10-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0002_rename_settings_projectsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='AMOJO_SCOPE_ID',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='AMOJO_SECRET',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
